### ISSUE TITLE
License missing from repository

### ISSUE THREAD

**Issue by rcjsuen** [RedBadgerStudio/project_engage_repository#2]
What kind of license are the code and assets of this project under? Could a `LICENSE.md` file be added to this repository?

**Comment by ink200601** [comment]
The reasoning for there not being a license on the project is simply because I don't have to time to review all of the license options, I can see what I can do but no promises that I'll use the right license for the project.

**Comment by ink200601** [comment]
I've Added an MIT license, feel free to do whatever you'd like!

**Comment by rcjsuen** [comment]
> The reasoning for there not being a license on the project is simply because I don't have to time to review all of the license options, I can see what I can do but no promises that I'll use the right license for the project.

I understand that it is never an easy decision what license should be used for software. Thank you for reviewing this question and adding a license file to the repository!

**Comment by ink200601** [comment]
No problem!
